// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'11c1d2e2ff38d0259d643cef2bfb38f490ed5b6fa447beb230d4988425748245'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date@1': { readonly output: 'pg/date@1'; readonly nullable: true };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time@1': { readonly output: 'pg/time@1'; readonly nullable: true };
      readonly 'pg/timestamp@1': { readonly output: 'pg/timestamp@1'; readonly nullable: true };
      readonly 'pg/timestamptz@1': { readonly output: 'pg/timestamptz@1'; readonly nullable: true };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/timestamp@1': { readonly output: 'sql/timestamp@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date@1': { readonly output: 'pg/date@1'; readonly nullable: true };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time@1': { readonly output: 'pg/time@1'; readonly nullable: true };
      readonly 'pg/timestamp@1': { readonly output: 'pg/timestamp@1'; readonly nullable: true };
      readonly 'pg/timestamptz@1': { readonly output: 'pg/timestamptz@1'; readonly nullable: true };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/timestamp@1': { readonly output: 'sql/timestamp@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Incident: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly service: CodecTypes['pg/text@1']['output'];
      readonly severity: CodecTypes['pg/text@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly owner: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly escalated: CodecTypes['pg/bool@1']['output'];
      readonly acknowledgedAt: CodecTypes['pg/timestamptz@1']['output'] | null;
      readonly resolvedAt: CodecTypes['pg/timestamptz@1']['output'] | null;
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly notes: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
    };
    readonly IncidentEvent: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly incidentId: CodecTypes['pg/int4@1']['output'];
      readonly type: CodecTypes['pg/text@1']['output'];
      readonly at: CodecTypes['pg/timestamptz@1']['output'];
      readonly actor: CodecTypes['pg/text@1']['output'];
      readonly details: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly MaintenanceWindow: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly service: CodecTypes['pg/text@1']['output'];
      readonly startsAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly endsAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly reason: CodecTypes['pg/text@1']['output'];
    };
    readonly Notification: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly incidentId: CodecTypes['pg/int4@1']['output'];
      readonly channel: CodecTypes['pg/text@1']['output'];
      readonly recipient: CodecTypes['pg/text@1']['output'];
      readonly message: CodecTypes['pg/text@1']['output'];
      readonly sentAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
    };
    readonly OnCall: {
      readonly team: CodecTypes['pg/text@1']['output'];
      readonly people: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
    };
    readonly Service: {
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly team: CodecTypes['pg/text@1']['output'];
      readonly critical: CodecTypes['pg/bool@1']['output'];
      readonly active: CodecTypes['pg/bool@1']['output'];
      readonly businessHoursOnly: CodecTypes['pg/bool@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Incident: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly service: CodecTypes['pg/text@1']['input'];
      readonly severity: CodecTypes['pg/text@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly owner: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly escalated: CodecTypes['pg/bool@1']['input'];
      readonly acknowledgedAt: CodecTypes['pg/timestamptz@1']['input'] | null;
      readonly resolvedAt: CodecTypes['pg/timestamptz@1']['input'] | null;
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly notes: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
    };
    readonly IncidentEvent: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly incidentId: CodecTypes['pg/int4@1']['input'];
      readonly type: CodecTypes['pg/text@1']['input'];
      readonly at: CodecTypes['pg/timestamptz@1']['input'];
      readonly actor: CodecTypes['pg/text@1']['input'];
      readonly details: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly MaintenanceWindow: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly service: CodecTypes['pg/text@1']['input'];
      readonly startsAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly endsAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly reason: CodecTypes['pg/text@1']['input'];
    };
    readonly Notification: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly incidentId: CodecTypes['pg/int4@1']['input'];
      readonly channel: CodecTypes['pg/text@1']['input'];
      readonly recipient: CodecTypes['pg/text@1']['input'];
      readonly message: CodecTypes['pg/text@1']['input'];
      readonly sentAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
    };
    readonly OnCall: {
      readonly team: CodecTypes['pg/text@1']['input'];
      readonly people: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
    };
    readonly Service: {
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly team: CodecTypes['pg/text@1']['input'];
      readonly critical: CodecTypes['pg/bool@1']['input'];
      readonly active: CodecTypes['pg/bool@1']['input'];
      readonly businessHoursOnly: CodecTypes['pg/bool@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly incident: {
      readonly acknowledgedAt: CodecTypes['pg/timestamptz@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly escalated: CodecTypes['pg/bool@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly notes: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly owner: CodecTypes['pg/text@1']['output'] | null;
      readonly resolvedAt: CodecTypes['pg/timestamptz@1']['output'] | null;
      readonly service: CodecTypes['pg/text@1']['output'];
      readonly severity: CodecTypes['pg/text@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly title: CodecTypes['pg/text@1']['output'];
    };
    readonly incidentEvent: {
      readonly actor: CodecTypes['pg/text@1']['output'];
      readonly at: CodecTypes['pg/timestamptz@1']['output'];
      readonly details: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly incidentId: CodecTypes['pg/int4@1']['output'];
      readonly type: CodecTypes['pg/text@1']['output'];
    };
    readonly maintenanceWindow: {
      readonly endsAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly reason: CodecTypes['pg/text@1']['output'];
      readonly service: CodecTypes['pg/text@1']['output'];
      readonly startsAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly notification: {
      readonly channel: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly incidentId: CodecTypes['pg/int4@1']['output'];
      readonly message: CodecTypes['pg/text@1']['output'];
      readonly recipient: CodecTypes['pg/text@1']['output'];
      readonly sentAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
    };
    readonly onCall: {
      readonly people: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly team: CodecTypes['pg/text@1']['output'];
    };
    readonly service: {
      readonly active: CodecTypes['pg/bool@1']['output'];
      readonly businessHoursOnly: CodecTypes['pg/bool@1']['output'];
      readonly critical: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly team: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly incident: {
      readonly acknowledgedAt: CodecTypes['pg/timestamptz@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly escalated: CodecTypes['pg/bool@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly notes: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly owner: CodecTypes['pg/text@1']['input'] | null;
      readonly resolvedAt: CodecTypes['pg/timestamptz@1']['input'] | null;
      readonly service: CodecTypes['pg/text@1']['input'];
      readonly severity: CodecTypes['pg/text@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly title: CodecTypes['pg/text@1']['input'];
    };
    readonly incidentEvent: {
      readonly actor: CodecTypes['pg/text@1']['input'];
      readonly at: CodecTypes['pg/timestamptz@1']['input'];
      readonly details: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly incidentId: CodecTypes['pg/int4@1']['input'];
      readonly type: CodecTypes['pg/text@1']['input'];
    };
    readonly maintenanceWindow: {
      readonly endsAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly reason: CodecTypes['pg/text@1']['input'];
      readonly service: CodecTypes['pg/text@1']['input'];
      readonly startsAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly notification: {
      readonly channel: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly incidentId: CodecTypes['pg/int4@1']['input'];
      readonly message: CodecTypes['pg/text@1']['input'];
      readonly recipient: CodecTypes['pg/text@1']['input'];
      readonly sentAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
    };
    readonly onCall: {
      readonly people: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly team: CodecTypes['pg/text@1']['input'];
    };
    readonly service: {
      readonly active: CodecTypes['pg/bool@1']['input'];
      readonly businessHoursOnly: CodecTypes['pg/bool@1']['input'];
      readonly critical: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly team: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly incident: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly service: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly severity: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'open'>;
                  };
                };
                readonly owner: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly escalated: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly acknowledgedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: true;
                };
                readonly resolvedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: true;
                };
                readonly tags: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly notes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly incidentEvent: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly incidentId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly actor: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly details: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'incidentEvent_incidentId_idx_20b6f3c9';
                  readonly prefix: 'incidentEvent_incidentId_idx';
                  readonly columns: readonly ['incidentId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'incidentEvent';
                    readonly columns: readonly ['incidentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'incident';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly maintenanceWindow: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly service: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly startsAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
                readonly endsAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
                readonly reason: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly notification: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly incidentId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly channel: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly recipient: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly message: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sentAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'notification_incidentId_idx_20b6f3c9';
                  readonly prefix: 'notification_incidentId_idx';
                  readonly columns: readonly ['incidentId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'notification';
                    readonly columns: readonly ['incidentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'incident';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly onCall: {
              columns: {
                readonly team: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly people: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['team'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly service: {
              columns: {
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly team: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly critical: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly businessHoursOnly: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['name'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly incident: { readonly namespace: 'public' & NamespaceId; readonly model: 'Incident' };
    readonly incidentEvent: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'IncidentEvent';
    };
    readonly service: { readonly namespace: 'public' & NamespaceId; readonly model: 'Service' };
    readonly onCall: { readonly namespace: 'public' & NamespaceId; readonly model: 'OnCall' };
    readonly maintenanceWindow: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'MaintenanceWindow';
    };
    readonly notification: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Notification';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Incident: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly service: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly severity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly owner: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly escalated: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly acknowledgedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly resolvedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly tags: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly notes: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
            };
            readonly relations: {
              readonly events: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'IncidentEvent';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['incidentId'];
                };
              };
              readonly notifications: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Notification';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['incidentId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'incident';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly title: { readonly column: 'title' };
                readonly service: { readonly column: 'service' };
                readonly severity: { readonly column: 'severity' };
                readonly status: { readonly column: 'status' };
                readonly owner: { readonly column: 'owner' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly escalated: { readonly column: 'escalated' };
                readonly acknowledgedAt: { readonly column: 'acknowledgedAt' };
                readonly resolvedAt: { readonly column: 'resolvedAt' };
                readonly tags: { readonly column: 'tags' };
                readonly notes: { readonly column: 'notes' };
              };
            };
          };
          readonly IncidentEvent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly incidentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly at: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly actor: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly details: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly incident: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Incident';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['incidentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'incidentEvent';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly incidentId: { readonly column: 'incidentId' };
                readonly type: { readonly column: 'type' };
                readonly at: { readonly column: 'at' };
                readonly actor: { readonly column: 'actor' };
                readonly details: { readonly column: 'details' };
              };
            };
          };
          readonly MaintenanceWindow: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly service: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly startsAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly endsAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly reason: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'maintenanceWindow';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly service: { readonly column: 'service' };
                readonly startsAt: { readonly column: 'startsAt' };
                readonly endsAt: { readonly column: 'endsAt' };
                readonly reason: { readonly column: 'reason' };
              };
            };
          };
          readonly Notification: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly incidentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly channel: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly recipient: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly message: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sentAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly incident: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Incident';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['incidentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'notification';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly incidentId: { readonly column: 'incidentId' };
                readonly channel: { readonly column: 'channel' };
                readonly recipient: { readonly column: 'recipient' };
                readonly message: { readonly column: 'message' };
                readonly sentAt: { readonly column: 'sentAt' };
                readonly status: { readonly column: 'status' };
              };
            };
          };
          readonly OnCall: {
            readonly fields: {
              readonly team: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly people: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'onCall';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly team: { readonly column: 'team' };
                readonly people: { readonly column: 'people' };
              };
            };
          };
          readonly Service: {
            readonly fields: {
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly team: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly critical: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly active: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly businessHoursOnly: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'service';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly name: { readonly column: 'name' };
                readonly team: { readonly column: 'team' };
                readonly critical: { readonly column: 'critical' };
                readonly active: { readonly column: 'active' };
                readonly businessHoursOnly: { readonly column: 'businessHoursOnly' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
